title: Agnes Coaker 
logo: "/images/professional-headshot.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Data Analyst
  <br><br>
  SQL | R | Various MI Tools
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/agnes-coaker/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
